name: DeityNether
version: 0.1
authors: [Cliff777, mbonachea, thejacoborg]
website: http://www.ImDeity.com/
load: STARTUP

main: com.imdeity.nether.DeityNether
commands:
  nether:
    description: Base nether command
    usage: /nether [args]