name: DeityNether
version: 0.1
authors: [Cliff777, mbonachea, thejacoborg]
website: http://www.imdeity.com/

main: com.imdeity.nether
commands:
  nether:
    description: Base nether command
    usage: /nether [args]